### ISSUE TITLE
stream.* fields showing as unknown type in Kibana index pattern 

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/integrations#95] opened 2020-06-18 16:53 UTC
When testing `system` package, I found out I can not filter using `stream.dataset` in Kibana Discover page. Here is what's shown in Kibana index pattern when running `system` package:
![Screenshot from 2020-06-17 17-40-17](https://user-images.githubusercontent.com/14081635/85049408-deffe100-b151-11ea-8091-90498e14be01.png)

But with a new agent, new test environment when testing aws package, I was able to use `stream.dataset` as a filter in Kibana Discover. Here is what's shown in Kibana index pattern when running `aws` package:
<img width="1250" alt="Screen Shot 2020-06-17 at 3 28 55 PM" src="https://user-images.githubusercontent.com/14081635/85048862-2639a200-b151-11ea-8604-abdacefc0bc1.png">

cc @fearful-symmetry @ycombinator

**Comment by ruflin** [comment] 2020-06-18 21:00
I think the problem is that the agent is still shipping this fields but @michalpristas plans to remove those?

**Comment by michalpristas** [comment] 2020-06-19 06:00
yes this will be removed on monday/tuesday latest

**Comment by mtojek** [comment] 2020-06-25 08:23
@ruflin @michalpristas any update on this?

**Comment by michalpristas** [comment] 2020-06-25 08:26
PR here: https://github.com/elastic/beats/pull/19356
testing before merging should be in today

**Comment by mtojek** [comment] 2020-07-01 07:40
@michalpristas if this is fixed, could you please close the issue?

**Closed** 2020-07-01 08:37 UTC
