### ISSUE TITLE
No error message shows up while adding invalid URL at Elastic synthesis integration.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/integrations#1300] opened 2021-07-08 07:51 UTC
**Kibana version:** 7.14 BC1 Kibana Cloud-QA environment

**Host OS and Browser version:** Chrome, Firefox and edge

**Preconditions:**
1. 7.14 BC1 Kibana Cloud-QA environment should be available.

**Build Details:**
```
BUILD 42367
COMMIT d417b7aaba7d337fd45da08ed75dcc2c7fdf56cb

```

**Steps to reproduce:**
	- Login to Kibana.
	- Navigate to Integrations tab.
	- Select Elastic synthesis integration and click on add button.
	- Provide any invalid value at URL field at step 2.
	- Observe, a confirmation success toast with 'add agent' fly-out appears.

**Expected result:**
- Error message should be displayed while adding invalid URL at Elastic synthesis integration.

**Recording:**

https://user-images.githubusercontent.com/72375798/124882734-4fdc9a00-dfee-11eb-99ba-f0adcc200830.mp4

**Comment by dikshachauhan-qasource** [comment] 2021-07-08 07:52
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment] 2021-07-08 08:32
Reviewed & Assigned to @jen-huang 

CC: @EricDavisX

**Comment by jen-huang** [comment] 2021-07-08 14:14
@elastic/uptime / @dominiqueclarke Is there expected to be this kind of validation in the Synthetics configuration UI?

**Comment by paulb-elastic** [comment] 2021-07-09 10:01
Thanks @dikshachauhan-qasource and @jen-huang for raising/questioning this, it’s an interesting point.

I guess a challenge here may be what is a valid URL, as monitors could be set up to point to something locally via just the hostname (e.g. `intranet` could be a valid host/URL to connect to and monitor with Synthetics (that would work in a browser on their network), although would fail traditional URL validation).

@drewpost how strict do you think we should be here with validation?

**Comment by andrewvc** [comment] 2021-07-19 22:25
Heartbeat is pretty lenient about validating inputs here, letting the underlying network implementation throw an error. Validating URLs isn't that simple, did you know `http://[2001:db8::1]:80` is a valid URL?

That said, it may be more helpful than not to focus on 98% of URLs than the edge cases, and just go with a regexp like the top answer here, and see if we see any real-world issues: https://stackoverflow.com/questions/161738/what-is-the-best-regular-expression-to-check-if-a-string-is-a-valid-url

**Comment by andrewvc** [comment] 2021-07-27 16:10
After meeting with the team today, we've decided that this is not a bug. Given the complexity of URLs, and the ease with which bad ones can be rectified, let's keep the behavior as-is, with the validation effectively happening downstream when the check executed

**Comment by jen-huang** [comment] 2021-07-27 18:05
Thanks Andrew and team for looking at this, I'm going to close this as won't fix.

**Closed by jen-huang** 2021-07-27 18:05 UTC
Labels: Team:Uptime

**Comment by dikshachauhan-qasource** [comment] 2021-07-28 04:03
Hi All,

Thanks for feedback and looking down into this.
