### ISSUE TITLE
[TSDB][elastic-package] Verify the support of multiple variants during system test when TSDB is enabled

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#8741] opened 2023-12-18 02:46 UTC
This problem was noticed during TSDB enablement of etcd datastream. Details can be found [here](https://github.com/elastic/integrations/pull/8649#issuecomment-1845883417).

When there multiple variants exist, the system test fails to run correctly for the second variant during CI/CD pipeline. 

In the case of etcd, the solution is to remove the multiple variants. This change is Ok considering all the variants mentioned are of version 3.x,  support of 2.x variant of etcd is deprecated. 

This issue is created to assess the impact of multiple variants in CI/CD pipeline system test. If the problem exists, the issue may be reported to the ecosystem team.

**Comment by agithomas** [comment] 2023-12-18 03:59
It is the same issue mentioned [here](https://github.com/elastic/elastic-package/issues/1365#issue-1817803601)

**Comment by agithomas** [comment] 2023-12-18 04:00
If the issue can be remediated with 8.8.1 upgrade, details regarding this must be added to the TSDB developer guidelines document.

**Comment by agithomas** [comment] 2024-01-04 07:05
With the changes, the test is supported in the local test, with multi-variants. 

I will be doing the CI/CD test , with test PR, where the problem was originally reported. 

```
--- Test results for package: etcd - START ---
╭─────────┬─────────────┬───────────┬───────────────────────────────┬────────┬────────────────╮
│ PACKAGE │ DATA STREAM │ TEST TYPE │ TEST NAME                     │ RESULT │   TIME ELAPSED │
├─────────┼─────────────┼───────────┼───────────────────────────────┼────────┼────────────────┤
│ etcd    │ metrics     │ system    │ default (variant: etcd_3_5_1) │ PASS   │ 1m0.161955391s │
│ etcd    │ metrics     │ system    │ default (variant: etcd_3_3_8) │ PASS   │  55.251495993s │
╰─────────┴─────────────┴───────────┴───────────────────────────────┴────────┴────────────────╯
--- Test results for package: etcd - END   ---
Done
```

**Comment by agithomas** [comment] 2024-01-04 09:01
With the upgrade to 8.8.1, multivariant support is present with TSDB enablement. 

As a next step, i will update the Guidelines document

**Comment by jsoriano** [comment] 2024-01-17 12:23
This seems to be the PR fixing the root cause in 8.8.1: https://github.com/elastic/elasticsearch/pull/96461

**Comment by andrewkroh** [comment] 2024-08-14 21:47
Closing b/c I think this is working now. Please reopen is this is still a problem.

**Closed by andrewkroh** 2024-08-14 21:47 UTC
