### ISSUE TITLE
Cannot index event publisher for MongoDB integration

### ISSUE THREAD

**Issue by yash-gill** [elastic/integrations#3025] opened 2022-04-07 09:13 UTC
ES, Kibana, Fleet Server versions: 7.17.0, 

MongoDB integration version: 1.3.1

Not able to get logs and metrics through Fleet integrations, the log file path and creds are fine but getting these in the logs:

`Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Date(2022, time.April, 3, 9, 31, 32, 745485040, time.Local), Meta:{"raw_index":"logs-mongodb.log-production_linux_servers"}, Fields:{"agent":{"ephemeral_id":"b9e65e7a-46c0-48cd-aca1-1543caa99661","hostname":"x.x.x","id":"82c349e4-74c4-4a33-8d6a-fd65c150bb8a","name":"x.x.x","type":"filebeat","version":"7.17.0"},"data_stream":{"dataset":"mongodb.log","namespace":"production_linux_servers","type":"logs"},"ecs":{"version":"1.12.0"},"elastic_agent":{"id":"82c349e4-74c4-4a33-8d6a-fd65c150bb8a","snapshot":false,"version":"7.17.0"},"event":{"dataset":"mongodb.log"},"host":{"architecture":"x86_64","containerized":false,"hostname":"x.x.x","id":"45eb2df2882c4780af7ccc66d6d30f21","ip":["x.x.x.x","xxxx::xxx:xxxx:xxxx:xxxx"],"mac":["xx:xx:x:x:x:x"],"name":"x.x.x","os":{"codename":"bionic","family":"debian","kernel":"4.15.0-151-generic","name":"Ubuntu","platform":"ubuntu","type":"linux","version":"18.04.4 LTS (Bionic Beaver)"}},"input":{"type":"log"},"log":{"file":{"path":"/var/log/mongodb/mongod.log"},"offset":188233011},"message":"2022-04-03T16:31:32.596Z I WRITE    [conn27759873] update x.SessionTable command: { q: { _id: \"c8a73f4731781814_2022040316\" }, u: { $set: { ClientId: \"c8a73f4731781814\", PrimaryUserId: null, SessionStartTime: new Date(1649003492351), SessionEndTime: new Date(1649003492351), SessionDuration: 0, PrimaryUserName: \"IIS APPPOOL\\x\", UserAgent: \"Mozilla/5.0 (Linux; Android 10; Lenovo TB-X306X Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.73 Safari/537.36\", ClientIPs: [ \"x.x.x.x\" ] } }, multi: false, upsert: true } planSummary: IDHACK keysExamined:0 docsExamined:0 nMatched:0 nModified:0 upsert:1 keysInserted:10 numYields:0 locks:{ Global: { acquireCount: { r: 1, w: 1 } }, Database: { acquireCount: { w: 1 } }, Collection: { acquireCount: { w: 1 } } } storage:{ data: { bytesRead: 43509, timeReadingMicros: 874 } } 241ms","tags":["mongodb-logs"]}, Private:file.State{Id:"native::3539854-2050", PrevId:"", Finished:false, Fileinfo:(*os.fileStat)(0xc000a7dad0), Source:"/var/log/mongodb/mongod.log", Offset:188233895, Timestamp:time.Date(2022, time.April, 2, 11, 38, 29, 901599115, time.Local), TTL:-1, Type:"log", Meta:map[string]string(nil), FileStateOS:file.StateOS{Inode:0x36038e, Device:0x802}, IdentifierName:"native"}, TimeSeries:false}, Flags:0x1, Cache:publisher.EventCache{m:common.MapStr(nil)}} (status=400): {"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"illegal_argument_exception","reason":"data stream timestamp field [@timestamp] is missing"}}, dropping event!`

Sidenote: could this be related to using `experimental: true` in fleet settings initially? Based on this [discussion](https://discuss.elastic.co/t/fleet-ui-is-unusable-due-to-timeout-errors/300936/12), I turned off that setting and also tried readding the integration as well as creating new policies after reinstalling all assets.

Please let me know about can be done here.

**Comment by yash-gill** [comment] 2022-04-30 07:12
Hi, any update? Tried several things, still not able to get it to work.

**Comment by andrewkroh** [comment] 2022-04-30 21:03
This is a risky operation, because if the pipeline fails before the timestamp is replaced then you get the problem here. The pipeline should be refactored

https://github.com/elastic/integrations/blob/4c43165a69299f91a8215141abaf03cfdeb3bd7b/packages/mongodb/data_stream/log/elasticsearch/ingest_pipeline/default.yml#L7-L9

**Comment by yash-gill** [comment] 2022-05-07 10:42
Hi @andrewkroh I'll be trying out your suggestion soon to avoid any downtime. For the time being, I just changed the default_pipeline in index settings from: `"logs-mongodb.log-1.3.1"` to  `"logs-mongodb.log-1.3.1-pipeline-plaintext"` and that allowed me to get the logs in Kibana at least, albeit without the right properties being mapped.

**Comment by ManojS-shetty** [comment] 2022-10-18 08:40
@yash-gill Can you please update the mongodb version to latest and try again to reproduce the same?

**Comment by ManojS-shetty** [comment] 2022-10-27 08:26
We are moving this to Done state as we are not seeing this error now in log ingesting. If you it is found again please report it and mention the steps to reproduce and version of the mongodb used.

**Closed** 2022-10-27 08:26 UTC
Labels: bug, Team:Integrations, Integration:MongoDB, Team:Service-Integrations
