### ISSUE TITLE
Error message shown up while adding Kafka integration (v0.3.6 on 7.12 BC2)

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/integrations#752] opened 2021-03-01 12:37 UTC
**Kibana version:**
7.12 BC2 Kibana Cloud environment 
BUILD 39000
COMMIT 4f65a5a1268fa78f1af9117d12312e1cee433376

**Steps to reproduce:**
1. Create a new policy in Fleet (no Agents assigned to this policy yet)
2. Add Integration 'Kafka' to this new policy.
4. Observe an error message is shown up. Screenshot attached for reference.

Expected Result:
No error message should be displayed while adding kafka integration to any Policy.

**Screenshots:** 
![image](https://user-images.githubusercontent.com/72375798/109497926-c99cce00-7ab8-11eb-9be1-59e78e0a4718.png)

**Comment by dikshachauhan-qasource** [comment] 2021-03-01 12:39
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment] 2021-03-01 12:48
Reviewed & assigned to @EricDavisX

**Comment by EricDavisX** [comment] 2021-03-01 20:43
I verified the issue and confirmed it is seen on v0.3.6 of the Kafka package, as the latest seen with a 7.12 stack currently.

I don't see any other Kafka packages going through the package-storage stages - @masci let me know if you need any help seeing this or discussing testing.  The team doesn't usually dive deep on any integrations other than System, Linux, Windows, and Endpoint - but we do exploratory tests and are happy to log bugs when we see them.  

for everyone, including @dikshachauhan-qasource foremost, we acknowledge prior discussion that some integrations Will Not function properly if there is no corresponding data pushing it, but since this is not even deployed to any Agent and fails at this stage it seems a clear bug.  And I assume in the package, if it is believed on Fleet side (or other) please do push it back with comment, etc.  Thanks.

**Comment by ycombinator** [comment] 2021-03-01 21:13
I'm able to repro this error with Kibana 8.0.0-SNAPSHOT as well. Grabbed the full stack trace for the error from the Kibana server log:

```
YAMLException: bad indentation of a sequence entry at line 2, column 17:
     - \"/opt/kafka*\"\"/logs/controller.log*\"
                    ^
    at generateError (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at readBlockSequence (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:962:7)
    at composeNode (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:1358:12)
    at readBlockMapping (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:1089:11)
    at composeNode (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:1525:3)
    at loadDocuments (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:1588:5)
    at load (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:1614:19)
    at safeLoad (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:1637:10)
    at compileTemplate (/usr/share/kibana/x-pack/plugins/fleet/server/services/epm/agent/agent.js:37:57)
    at _compilePackageStream (/usr/share/kibana/x-pack/plugins/fleet/server/services/package_policy.js:534:43)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at _compilePackageStreams (/usr/share/kibana/x-pack/plugins/fleet/server/services/package_policy.js:495:10) {
  reason: 'bad indentation of a sequence entry',
  mark: Mark {
    name: null,
    buffer: 'paths:\
' +
      ' - \"/opt/kafka*\"\"/logs/controller.log*\"\
' +
      ' - \"/opt/kafka*\"\"/logs/server.log*\"\
' +
      ' - \"/opt/kafka*\"\"/logs/state-change.log*\"\
' +
      ' - \"/opt/kafka*\"\"/logs/kafka-*.log*\"\
' +
      'exclude_files: [\".gz$\"]\
' +
      'multiline:\
' +
      \"  pattern: '^\\\\['\
\" +
      '  negate: true\
' +
      '  match: after\
' +
      'processors:\
' +
      '- add_locale: ~\
' +
      '\\x00',
    position: 23,
    line: 1,
    column: 16
  }
}
```

**Comment by ycombinator** [comment] 2021-03-01 21:58
Still not sure if this is a Fleet UI bug or an issue in the `kafka` package itself. But the part of the package that's being reported in the error is this: https://github.com/elastic/integrations/blob/06284f69bb05e2275337f5d740c03ea5e73410ba/packages/kafka/data_stream/log/agent/stream/log.yml.hbs#L3

**Comment by jsoriano** [comment] 2021-03-02 10:59
> Still not sure if this is a Fleet UI bug or an issue in the `kafka` package itself. But the part of the package that's being reported in the error is this:
> 
> https://github.com/elastic/integrations/blob/06284f69bb05e2275337f5d740c03ea5e73410ba/packages/kafka/data_stream/log/agent/stream/log.yml.hbs#L3

Yep, this configuration concatenates two variables this way. This works in Filebeat and used to work in Fleet (at least till 7.11).

It seems that now double-quoutes are being added to each placeholder, generating bad yaml:
```
- "/opt/kafka*""/logs/controller.log*"
```

This looks like some change in fleet.

**Comment by exekias** [comment] 2021-03-02 11:01
Can someone from the @elastic/fleet team confirm? I wonder if this new behavior is expected or this can be considered a bug in the UI

**Comment by mtojek** [comment] 2021-03-02 11:28
I suspect two issues:

1. Kafka package: 
    Double dots and slash look suspicious here: https://github.com/elastic/integrations/blob/master/packages/kafka/data_stream/log/agent/stream/log.yml.hbs#L3

2. Kibana implementation: 
    Kibana doesn't play well in terms of vars concatenation: https://github.com/elastic/kibana/blob/master/x-pack/plugins/fleet/server/services/epm/agent/agent.ts#L68

For example:
```hbs
paths:
{{#each paths as |path i|}}
- {{kafka_home}}{{path}}
{{/each}}
```

results in: `"/opt/kafka*""/logs/controller.log*"`

@skh Could you please confirm the issue no. 2?

**Comment by skh** [comment] 2021-03-02 13:19
Maybe I was overeager in the fix for https://github.com/elastic/kibana/issues/91401 .

What I was trying to do is enclose strings in double quotes that contained characters with special meaning in yaml, because we had parsing errors on `*` which is used as a wildcard in strings.

From this list of characters, which would you recommend to take out of this special handling? `{` and `}` obviously from the bug you're seeing, but are there more?

```
  // List of special chars that may lead to YAML parsing errors when not quoted.
  // See YAML specification section 5.3 Indicator characters
  // https://yaml.org/spec/1.2/spec.html#id2772075
  const yamlSpecialCharsRegex = /[{}\[\],&*?|\-<>=!%@:]/;
```
(from https://github.com/elastic/kibana/blob/master/x-pack/plugins/fleet/server/services/epm/agent/agent.ts#L60-L71 )

**Comment by mtojek** [comment] 2021-03-02 13:22
Actually I suggest to rethink the idea of escaping here as it will always harm concatenation. Maybe we should consider the package as the only source of truth? Whether a variable should be escaped or not.

**Comment by skh** [comment] 2021-03-02 13:24
The `*` in question was a `"*"` in the package, but something already stripped the double quotes which lead to the original bug.

**Comment by skh** [comment] 2021-03-02 15:31
I spoke too soon. The issues are the wildcards in the values `/opt/kafka*` and e.g. `/logs/controller.log*`. I'll spare you the details, and I'm preparing a fix for Fleet/Kibana.

**Comment by EricDavisX** [comment] 2021-03-02 16:12
transferring to Kibana repo.

**Comment by skh** [comment] 2021-03-15 13:21
Fixed in https://github.com/elastic/kibana/pull/93585

**Closed by skh** 2021-03-15 13:21 UTC
Labels: High, Team:Fleet, Team:Integrations, bug
