### ISSUE TITLE
[Integrations][Fleet]: On clicking AWS dynamodb user is navigated to AWS overview page.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/integrations#1293] opened 2021-07-07 10:26 UTC
**Kibana version:** 7.14.0 BC-1 Kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
Build: 42292
Commit: 071a74e02f82b79a4a10026b5c9e02d593112fd4
```

**Preconditions:**
1. 7.14.0 BC-1 Kibana cloud environment should be available.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Integrations tab.
3. Search AWS Dynamodb and click on it.
4. Observe user is navigated to Aws overview page.

**Reference Ticket:**
https://github.com/elastic/kibana/issues/93315

**Expected Result:**
As per integrations granularity feature user should be navigated to AWS dynamodb overview page.

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/124743402-565e0980-df3b-11eb-9ee0-af6a37b57ffb.mp4

**NOTE:**
User is unable to add AWS with only dynamodb enable.

**Comment by manishgupta-qasource** [comment] 2021-07-07 10:28
Reviewed & assigned to @jen-huang 

CC: @EricDavisX

**Comment by kaiyan-sheng** [comment] 2021-07-07 14:06
This is the same behavior I see in https://github.com/elastic/kibana/issues/104241

**Comment by jen-huang** [comment] 2021-07-07 14:33
Closing as dupe of elastic/kibana#104241.

**Closed by jen-huang** 2021-07-07 14:33 UTC
Labels: Team:Fleet, Team:Integrations, bug, impact:high, release-pending
