### ISSUE TITLE
Error when running the elastic agent on Windows

### ISSUE THREAD

**Issue by narph** [elastic/integrations#93] opened 2020-06-17 14:09 UTC
I have packaged the latest version of the elastic agent and tried it out and I am getting:
```
app/app.go[214]: unknown error
2020-06-17T16:00:14+02:00 ERROR reporter.go:47  2020-06-17T16:00:14+02:00: type: 'ERROR': sub_type: 'CONFIG' message: Application: metricbeat[912f7464-4612-4b87-8038-139ff8b67054]: application 'metricbeat--8.0.0' crashed: /go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/core/plugin/app/app.go[214]: unknown error
2020-06-17T16:00:17+02:00 ERROR reporter.go:47  2020-06-17T16:00:17+02:00: type: 'ERROR': sub_type: 'CONFIG' message: Application: metricbeat[912f7464-4612-4b87-8038-139ff8b67054]: application 'metricbeat--8.0.0' crashed: /go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/core/plugin/app/app.go[214]: unknown error
2020-06-17T16:00:20+02:00 ERROR reporter.go:47  2020-06-17T16:00:20+02:00: type: 'ERROR': sub_type: 'CONFIG' message: Application: metricbeat[912f7464-4612-4b87-8038-139ff8b67054]: application 'metricbeat--8.0.0' crashed: /go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/core/plugin/app/app.go[214]: unknown error
2020-06-17T16:00:23+02:00 ERROR reporter.go:47  2020-06-17T16:00:23+02:00: type: 'ERROR': sub_type: 'CONFIG' message: Application: metricbeat[912f7464-4612-4b87-8038-139ff8b67054]: application 'metricbeat--8.0.0' crashed: /go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/core/plugin/app/app.go[214]: unknown error
2020-06-17T16:00:26+02:00 ERROR reporter.go:47  2020-06-17T16:00:26+02:00: type: 'ERROR': sub_type: 'CONFIG' message: Application: metricbeat[912f7464-4612-4b87-8038-139ff8b67054]: application 'metricbeat--8.0.0' crashed: /go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/core/plugin/app/app.go[214]: unknown error
```
Are there are any tests or any steps on how to debug this? 
No data coming in as well.

cc @michalpristas

**Comment by michalpristas** [comment] 2020-06-17 14:14
maybe related
https://github.com/elastic/beats/issues/19241
https://github.com/elastic/beats/issues/19215

metricbeat logs would be helpful

**Comment by narph** [comment] 2020-06-17 14:19
Filebeat and metricbeat logs:
[logs.zip](https://github.com/elastic/integrations/files/4793088/logs.zip)

console output [consoleoutput.txt](https://github.com/elastic/integrations/files/4793105/consoleoutput.txt)

**Comment by ph** [comment] 2020-06-17 22:01
is that with 7.8 or 8.0 ?

**Comment by michalpristas** [comment] 2020-06-18 15:20
master, i tried to repro with no luck, i'm working with mariana to find out where the problem is

**Comment by ph** [comment] 2020-06-18 16:15
Is the issue is elastic/beats#19241? I would like to track in our board as a bug, maybe transferring this issue is the solution.

**Comment by michalpristas** [comment] 2020-06-25 12:39
could not reproduce the issue, i will have a zoom with mariana to get more information and see this in action

**Comment by michalpristas** [comment] 2020-06-26 08:32
got in touch with @narph we went through environment and aligned versions of different parts. everything seems working now

**Closed by michalpristas** 2020-06-26 08:32 UTC

**Comment by ph** [comment] 2020-06-26 12:52
@michalpristas Anything we could do to detect that situation on our side? maybe we could create an issue?
