### ISSUE TITLE
Kubernetes overview dashboard: metric visualization displays incorrect data

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/integrations#2159] opened 2021-11-15 11:46 UTC
This issue consist of few parts:
- when initially loading the dashboard number of nodes, number of deployments and pods numbers are `0`, the same might happen when refreshing visualizations
- changing time range might affect the umber of desired pods and available pods? (I assume that it might be related to the type of aggregation, which is sum, but still it is not clear)
see attached:
https://user-images.githubusercontent.com/28299531/141775571-1e2953cf-90e2-4ab0-a8d8-0a356f834ba5.mov

**Comment by ChrsMark** [comment] 2022-02-01 10:20
Some thoughts:

1. Time range is changing the aggregation range and this can result in different results.
2. I'm not sure if the visualisation is correct at all. We only use the value from the deployment Pods and we leave out the Pods which belong to Daemonsets for example. This can be misleading to my mind. See [state_deployment](https://github.com/elastic/beats/blob/39554cd10c1f790644f7f4bad346ff88bc0ef7e7/metricbeat/module/kubernetes/state_deployment/state_deployment.go#L47) and [state_daemonset](https://github.com/elastic/beats/blob/39554cd10c1f790644f7f4bad346ff88bc0ef7e7/metricbeat/module/kubernetes/state_daemonset/state_daemonset.go#L45)

**Comment by flash1293** [comment] 2022-02-02 10:56
As discussed in https://github.com/elastic/sdh-kibana/issues/2525 it's currently not possible to do a visualization like "sum up the last values of multiple time series identified by more than one label field" in TSVB (you can approximate by making sure the interval of the visualization and the interval of the beat line up, but this has other downsides as well).

It's possible in general to do this kind of aggregation using Elasticsearch by doing a date histogram with nested terms on the multiple label fields with a "top metric" agg in there, then using sum buckets on each level (or vega transformation capabilities) to calculate the final number. However, there are some downsides to this, too:
* The vega vis is not referencing the index pattern saved object, instead the string is inlined in the vega spec - it won't be possible to bulk-change the index pattern for all visualizations by changing the index pattern saved object, instead every visualization has to be touched inidividually
* It's harder for users to do changes as they have to interact with the vega UI directly
* We won't be able to 100% replicate the look of the visualization (e.g. what happens if there is no data found)

**Comment by flash1293** [comment] 2022-02-02 18:14
@ChrsMark Ideally we would like to avoid Vega in the default dashboards - if we would have a better understanding of the impact of this, we could build this feature into TSVB as a more robust stopgap solution with medium effort. Do you know where we can get this information?

**Comment by ChrsMark** [comment] 2022-02-03 09:34
@flash1293 I will need to investigate this in order collect some more information. Let me come back to you with more details asap.

**Comment by kaiyan-sheng** [comment] 2022-02-08 08:01
@ChrsMark We don't have the exact same use case in visualizations created for AWS integrations but I was able to see this same issue by creating a test visualization to display sum of a random metric with Last value data time range mode. I think the problem here is the `interval: auto` does not actually recognize the collection period `metricset.period` value and adjust based on that. Also this result should not change when the time range changes.

https://user-images.githubusercontent.com/14081635/152942641-0e9f0291-f126-4d66-ac76-e057a4246f0e.mp4
(This video is only for testing the TSVB, not meaningful or useful at all.)

While looking at this issue, I saw this [discuss forum ticket](https://discuss.elastic.co/t/tsvb-value-is-0-when-time-filter-set-to-today-and-data-time-range-mode-set-to-last-value/246719) and found it helpful. 

@fearful-symmetry If I remember correctly, similar issues were happening in the system module dashboard. Do you have any insights here?

**Comment by flash1293** [comment] 2022-02-08 08:13
I can confirm the “auto” interval in TSVB isn’t and was never connected to the collection period. It’s calculated based on the length of the time range and some advanced settings which are set per space (target number of buckets, max number of buckets)

the linked discuss post is a related issue, but it’s not exactly the problem we are seeing here. Even if the end of the time range is set to “now”, missing or wrong data can occur.

**Comment by flash1293** [comment] 2022-02-08 08:17
The approach of splitting by all relevant labels, then taking the last value each of the desired field and summing up the series into a single value will be much more robust because it doesn’t rely on knowing the collection period - even if the last bucket is longer than the collection period it will “deduplicate” and only sum up the last value per series which looks like what we need here

**Comment by flash1293** [comment] 2022-02-08 08:22
Good point @ChrsMark - I definitely came across this use case outside of beat integrations. @ghudgins what do you think about prioritizing the multi field split in TSVB and pushing out another gap filling issue instead?

**Comment by ghudgins** [comment] 2022-02-08 14:17
agreed - i'll take a look this morning at the 8.2 plan

**Comment by ChrsMark** [comment] 2022-02-08 14:27
Thank you folks @flash1293 @ghudgins !

**Comment by ChrsMark** [comment] 2022-02-08 14:28
Fyi I also tried with Lens Metric visualisation but it doesn't seem to be possible to have the wanted result.

**Comment by nugroho-exp** [comment] 2022-03-16 09:31
Is there any update on this issue?

We have the same issue, different time selection gives different desired pods and available pods number. For example with Last 30 minutes I get 46 desired pods  but when I set to last 1 hour I get 92 pods.

**Comment by flash1293** [comment] 2022-03-17 09:47
@nugroho-exp could you check whether the "Skip last bucket" option is set to true? 

Also, in 8.2 TSVB will be able to group by multiple fields: https://github.com/elastic/kibana/pull/126015 which will allow for a more stable version of this calculation

**Comment by ChrsMark** [comment] 2022-03-17 09:56
> kube_deployment_spec_replicas{namespace="default",deployment="hello-python"} 1

So the idea is that a timeseries like `kube_deployment_spec_replicas{namespace="default",deployment="hello-python"}` will produce a field `composite_labels_field` with the value of `default_hello-python`?

That could be done in Metricbeat however I wonder if we really want to store and expose this field actually, isn't this something hacky that would also be visible to everyone?

**Comment by flash1293** [comment] 2022-03-17 10:01
> That could be done in Metricbeat however I wonder if we really want to store and expose this field actually, isn't this something hacky that would also be visible to everyone?

@ChrsMark It is, that's why we introduced https://github.com/elastic/kibana/pull/126015 so it can be done at query time as part of regular TSVB.

**Comment by nugroho-exp** [comment] 2022-03-17 10:35
> @nugroho-exp could you check whether the "Skip last bucket" option is set to true?
> 
> Also, in 8.2 TSVB will be able to group by multiple fields: [elastic/kibana#126015](https://github.com/elastic/kibana/pull/126015) which will allow for a more stable version of this calculation

I use the latest version of the integration (1.17.2) and I see that the desired pods and available pods visualization has "Drop last bucket" set to Yes.

![image](https://user-images.githubusercontent.com/35025861/158791089-ecd246fe-11d4-4205-af4c-75987183c99d.png)

**Comment by flash1293** [comment] 2022-03-17 10:40
@nugroho-exp Thanks for confirming - in that case we can't make it more precise without changing to multi field grouping together with series agg as described above.

**Comment by ChrsMark** [comment] 2022-03-17 11:08
@flash1293 so at the moment the suggestion is to actually store all labels in one field like `default_hello-pytho`?

**Comment by flash1293** [comment] 2022-03-17 11:23
Discussed offline with @ChrsMark and this is the configuration we should shoot for (no changes necessary on the data structure side): Field names are just examples
<img width="2234" alt="Screenshot 2022-03-17 at 12 21 44" src="https://user-images.githubusercontent.com/1508364/158798692-bac7c4a3-2fa0-49ca-8136-8c66c805b94c.png">

<img width="576" alt="Screenshot 2022-03-17 at 12 22 58" src="https://user-images.githubusercontent.com/1508364/158798718-01e617f0-b60c-4ed7-8888-1c8e2c8f94c4.png">

**Comment by ChrsMark** [comment] 2022-03-22 15:11
Beats' PR: https://github.com/elastic/beats/pull/30913 ☑️

**Comment by ChrsMark** [comment] 2022-03-30 11:00
PRs merged. Closing this one by now.

**Closed by ChrsMark** 2022-03-30 11:00 UTC
Labels: release-pending, v8.2.0, 8.2 candidate
