### ISSUE TITLE
[Stack Monitoring] Missing mapping for "event.created" missing in the integration packages

### ISSUE THREAD

**Issue by crespocarlos** [elastic/integrations#5869] opened 2023-04-12 09:29 UTC
Some SM integration packages data-streams are missing the mapping for the `event.created` field, which causes them to be mapped as `keyword` and not `date`.

Here are a few examples of data streams that are missing this mapping:

- Elasticsearch
  - gc
  - server
  - deprecation
  - slowlog
- Kibana 
  - log
  - audit
- Logstash
  - log 

It might be interesting to make sure the SM packages contain all necessary `event` fields mapped

```
- external: ecs
  name: event.ingested
- external: ecs
  name: event.kind
- external: ecs
  name: event.category
- external: ecs
  name: event.type
- external: ecs
  name: event.created
- external: ecs
  name: event.original
- external: ecs
```

### Acceptance criteria

- `event.date` is mapped as `date`

**Comment by jennypavlova** [comment] 2023-04-28 13:02
The `event.created` is already mapped in this [PR](https://github.com/elastic/integrations/pull/5776/files) - Looks duplicate of https://github.com/elastic/integrations/issues/5774. I am adding the other missing event fields mentioned in this issue and will open a PR.

**Closed** 2023-05-04 16:15 UTC
Labels: bug, Integration:Elasticsearch, Integration:Kibana, Integration:Logstash, Team:Infra Monitoring UI
