### ISSUE TITLE
[cisco_duo] Authentication Logs dashboard won't load in Kibana 8.x

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#3023] opened 2022-04-07 02:21 UTC
The "[Cisco Duo] Authentication Logs" [dashboard](https://github.com/elastic/integrations/blob/3250d813f95cdd8a481e0017f43472769c9df17c/packages/cisco_duo/kibana/dashboard/cisco_duo-bd7d4870-0fbe-11ec-8b4b-67126a72b1d4.json) will not load in Kibana 8.x (tested 8.1.2 and 8.2.0-SNAPSHOT). It does load in 7.17.2. The package version being tested is 1.1.0 ([changelog](https://docs.elastic.co/en/integrations/cisco_duo#changelog)). The error is:

> Error encountered while loading saved dashboard: Could not find reference for kibanaSavedObjectMeta.searchSourceJSON.index

<img width="330" alt="Screen Shot 2022-04-06 at 22 06 19" src="https://user-images.githubusercontent.com/4565752/162106945-0065f046-1d67-4c32-8a38-1795ce243a9b.png">

### Steps to Reproduce

1. Navigate to the Cisco Duo integration page ( (http://localhost:5601/app/integrations/detail/cisco_duo-1.1.1/settings).
2. Click on Settings.
3. Click install assets.
4. Click on the Assets tab.
5. Open the `[Cisco Duo] Authentication Logs` dashboard.
6. Observe the error.

### Questions

- Was there a breaking change in Kibana?
- What can we do to correct the dashboard and have it work in 7.17 and 8.x?
- Does the problem affect other dashboards in other integration and can we detect it before our users do?

**Comment by flash1293** [comment] 2022-04-07 10:12
I looked into this and the issue is that the reference to the `index-pattern` saved object is missing. Maybe the reference got cleaned up by someone because it looked redundant? There was a bug in this area (https://github.com/elastic/kibana/pull/126499) and it got fixed in a way that works as long as the references haven't been edited (which I suspect happened for this specific case).

The bug is that the name of the index was not removed from the inlined vis (`"index": "logs-*"`)while being correctly extraced to the `references` section of the dashboard at the same time. The fix checks whether this is the case and tries to overwrite the local index name with the name of the saved object from the references array. This works as long as the references are still there.

This dashboard is similar (it was created during the time we had that bug), but it wasn't edited so it loads fine:
https://github.com/elastic/integrations/blob/84f43f3f0f53d0dbe2bf451ae79ae3b511b6acc1/packages/ti_threatq/kibana/dashboard/ti_threatq-a05fd810-78f1-11ec-a97c-7db1518ab848.json#L117

These are the references which are missing for the Cisco Duo auth logs:
https://github.com/elastic/integrations/blob/84f43f3f0f53d0dbe2bf451ae79ae3b511b6acc1/packages/ti_threatq/kibana/dashboard/ti_threatq-a05fd810-78f1-11ec-a97c-7db1518ab848.json#L779-L793

Please note that in this case the index pattern string and the id of the `index-pattern` saved object are both `logs-*`, but this is not guaranteed and the id in the references array might be changed by Kibana based on a number of factors. That's why any reference to an `index-pattern` saved object always needs to be called out it the `references` array (not as part of the inlined panel visualization definition)..

In case of https://github.com/elastic/integrations/blob/daf0b678f4fc9fb20610c60fe9bc560c6f159454/packages/cisco_duo/kibana/dashboard/cisco_duo-bd7d4870-0fbe-11ec-8b4b-67126a72b1d4.json the following references are missing:

```
        {
            "id": "logs-*",
            "name": "14cc4daa-2411-4927-be9d-20fc287bd46f:kibanaSavedObjectMeta.searchSourceJSON.index",
            "type": "index-pattern"
        },
        {
            "id": "logs-*",
            "name": "14cc4daa-2411-4927-be9d-20fc287bd46f:kibanaSavedObjectMeta.searchSourceJSON.filter[0].meta.index",
            "type": "index-pattern"
        },
        {
            "id": "logs-*",
            "name": "42f72b64-1bbf-49bd-909a-af8fcbc4c4e9:kibanaSavedObjectMeta.searchSourceJSON.index",
            "type": "index-pattern"
        },
        {
            "id": "logs-*",
            "name": bbabe39a-d588-40c3-81d5-fcfe6448b0ff:kibanaSavedObjectMeta.searchSourceJSON.index",
            "type": "index-pattern"
        },
```

I found one other dashboard with a similar problem - verified the same thing is happening (Cassandra integration): https://github.com/elastic/integrations/blob/b5eaf5d8011d5bd018f932b0333b4ae539c1dc25/packages/cassandra/kibana/dashboard/cassandra-dd325020-1f8b-11ec-ba68-fbf426daf104.json

In this case, it seems like the panel ids have been edited but the reference names weren't adjusted accordingly:

panel `2` needs a reference to the logs index pattern: https://github.com/elastic/integrations/blob/b5eaf5d8011d5bd018f932b0333b4ae539c1dc25/packages/cassandra/kibana/dashboard/cassandra-dd325020-1f8b-11ec-ba68-fbf426daf104.json#L141

But there's only a reference for the non-existing panel `9dfed84a-9a46-4e48-b069-db09e3e10b9a`:
https://github.com/elastic/integrations/blob/b5eaf5d8011d5bd018f932b0333b4ae539c1dc25/packages/cassandra/kibana/dashboard/cassandra-dd325020-1f8b-11ec-ba68-fbf426daf104.json#L187

In this case
```
        {
            "id": "logs-*",
            "name": "9dfed84a-9a46-4e48-b069-db09e3e10b9a:kibanaSavedObjectMeta.searchSourceJSON.filter[0].meta.index",
            "type": "index-pattern"
        },
```

should be turned into

```
        {
            "id": "logs-*",
            "name": "2:kibanaSavedObjectMeta.searchSourceJSON.filter[0].meta.index",
            "type": "index-pattern"
        },
```

I'm not sure whether this happened because the json files were manually edited or because they were exported from a Kibana snapshot version (it says `7.15.0-SNAPSHOT` in these files). However in both cases problems like this can sneak in because functionality can still change and during development we can only consider behavior for released versions and unedited export files - often these problems are very subtle and don't necessarily show up right away when checking the dashboard.

**Comment by flash1293** [comment] 2022-04-07 10:18
Happy to discuss how we can avoid problems like this in the future - I understand how it often makes sense to use a snapshot version to build dashboards (in case they are using features which are introduced in the current version). cc @ruflin a great topic for our sync.

**Comment by ruflin** [comment] 2022-04-07 14:39
@flash1293 If the data view would be part of the visualisation, we would not have the issue of a reference ;-)

**Comment by flash1293** [comment] 2022-04-07 16:05
Should I open a separate issue for the cassandra case?

**Comment by andrewkroh** [comment] 2022-04-07 16:09
I created an issue for Cassandra at #3031.

**Closed** 2022-04-11 17:55 UTC
Labels: bug, dashboard, integration:Cisco Duo
