### ISSUE TITLE
[Elastic Agent] Create the Elastic Agent package

### ISSUE THREAD

**Issue by nchaulet** [elastic/integrations#350] opened 2020-10-28 14:44 UTC
## Description 

Work in progress 

We should create an Elastic Agent package that will be installed by default in Fleet.

This package should defined index template for logs-elastic_agent... metrics-elastic_agent

**Comment by masci** [comment] 2020-12-24 14:00
duplicate of https://github.com/elastic/integrations/issues/434

**Closed by masci** 2020-12-24 14:00 UTC
Labels: Team:Ingest Management, v7.11.0
