### ISSUE TITLE
[InfluxDB] Shard disk size panel from Status metrics dashboard contains error

### ISSUE THREAD

**Issue by rajvi-elastic** [elastic/integrations#5506] opened 2023-03-10 13:46 UTC
**Description**

Shard disk size [InfluxDB Metrics] panel is showing below error:

> Field influxdb.status.storage_shard_disk_size not found

When we checked in the dashboard, [influxdb.status.storage_shard_disk_size](https://github.com/elastic/integrations/blob/main/packages/influxdb/kibana/dashboard/influxdb-ccddb0c0-276e-11ed-8cd7-b31b0e0c177f.json#L1296) field is used in the dashbaord panel. However, in `fields.yml` the mapping is defined for [influxdb.status.storage.shard_disk_size](https://github.com/elastic/integrations/blob/main/packages/influxdb/data_stream/status/fields/fields.yml#L124) field .

Below is the screenshot for the dashboard. In 8.3.0, the visualization is not getting populated because of the wrong field is configured in the panel.
![image](https://user-images.githubusercontent.com/124889398/224330841-e1cb3cd9-36e2-437a-a128-ab6f9fe6b9ea.png)

When we migrated this dashboard to the lens it is showing the error.
![image](https://user-images.githubusercontent.com/124889398/224331402-278e6ed5-0bdd-425e-ae23-045909df0227.png)

**Comment by agithomas** [comment] 2023-03-22 11:02
The issue is closed by https://github.com/elastic/integrations/pull/5312

**Closed** 2023-03-23 03:17 UTC
Labels: bug, integration, dashboard, Integration:InfluxDB
