### ISSUE TITLE
K8s Integration does not report correct container.id when container restarts

### ISSUE THREAD

**Issue by gizas** [elastic/integrations#5348] opened 2023-02-21 15:02 UTC
**Issue**

Customer deploys pod with several containers. Elastic Agent with Kubernetes Integration installed is used to monitor the **logs** of given pod's containers. Customer reported  that `container.id`  in Elasticsearch matches the actual container id as reported by kubectl.

Container is being restarted. After restart, the container ids dont match the new assigned container ids. 

**Relevant Screenshot**

![pod-id-constant-something-wrong](https://user-images.githubusercontent.com/1685415/220380797-c74ea2ac-5e5e-4e6b-9ed5-1a8029de7aaa.PNG)

**Comment by sunileman** [comment] 2023-02-22 04:34
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/12245219/220522233-143a59ab-5cce-4be6-a702-4c6bbdaca4f6.png">

K8s container logs are by default fetched using 
`/var/log/containers/*${kubernetes.container.id}.log`

During our debug session, we found container id did not match the container id found in the log file path.  

Where and how is `kubernetes.container.id` set?  In the context of K8s, I understand where `kubernetes.container.id` comes from.  I don't understand how our integration uses it.  The mismatch combo of `container.id`, logfile container id, and `kubernetes.container.id` is puzzling.

**Comment by gizas** [comment] 2023-02-22 15:32
I have managed to replicate the scenario of the user where the containers restart with updated manifest of https://github.com/elastic/integrations/issues/5348#issuecomment-1438661858, but everything seems to work!

Long story short the container.id is recognised correctly for restarted container.
This is the busybox that restarts every 60 sec
![Screenshot 2023-02-22 at 5 02 11 PM](https://user-images.githubusercontent.com/1685415/220664369-ccc69082-8225-4e96-86ce-00da70d1ebbe.png)

Those are the 
![Screenshot 2023-02-22 at 5 01 44 PM](https://user-images.githubusercontent.com/1685415/220664389-01752665-c962-4e5d-ad3e-3674b4df5a0b.png)

The relevant kubectl output:
```yaml
 kubectl describe pod -n development multi-container-pod
Name:             multi-container-pod
Namespace:        development
Priority:         0
Service Account:  default
Node:             pas-control-plane/172.20.0.2
Start Time:       Wed, 22 Feb 2023 16:46:13 +0200
Labels:           <none>
Annotations:      <none>
Status:           Running
IP:               10.244.0.20
IPs:
  IP:  10.244.0.20
Containers:
  container-1:
    Container ID:   containerd://80ece243fc07e9c6373b9eee8f856e5dfc21c9a0546a7f248c9b6e68b49e43e6
    Image:          nginx
      container-2:
    Container ID:  containerd://1b8800bb3c7eb1020d4c57fc79e07888da72c970789787e5c56d5161259b4d0e
   Image: alpine
      hello:
    Container ID:  containerd://b23931a68125a444ef97509fc190f86dfd3d747c4f8d5f5e2bf0ba3b6bfeedbf
    Image:         busybox:1.28
  [output was truncated]
```

Some remarks for all the comments made above:
1. This is the policy I used in my tests. Only logs are enabled. Just to ensure that no other datastream can ingest container.id
![Screenshot 2023-02-22 at 12 07 29 PM](https://user-images.githubusercontent.com/1685415/220665573-7f64ae77-7d7c-4a96-ba1e-024570e4d212.png)

2. Kubernetes.pod.uid not to be mixed with container.id field. (UId is unique per [pod](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids))
```yaml
kgp -n development multi-container-pod -o jsonpath='{.metadata.uid}'
2ef5500e-4f3c-4326-825c-cf2ca220baa
```

3. Indeed K8s container logs are by default fetched using
/var/log/containers/*${kubernetes.container.id}.log

This refers to https://www.elastic.co/guide/en/fleet/master/kubernetes-provider.html field and should be the same with the container.id you see ingested in Kibana Discovery
 
4. In order to see kibana entry for the restarted container you will need a successful log entry in to be created inside /var/log/ folder. So it might take sometime until next restart of container to see the entry.

Can we please verify with customer the id mismatch again (not to compare with uid)? Do the restart containers produce log entries in respected files? Is our policy correct and user cares only for logs ?

**Comment by ty-elastic** [comment] 2023-02-22 15:40
Thanks, @gizas . Indeed, `pod.uid` is not the same as `container.id`. If you look at the screenshot attached in the issue, you'll also see `container.id`, which you'll note does not match the container.id encoded in the `log.file.path` field. I pinned `pod.uid` just to show that it is the container that is restarting, not the pod (e.g., I `pod.uid` holds constant while `log.file.path` changes while `container.id` stays stuck on first instance of container in pod).

these containers in question log a lot of data; we did wait some time after pod restart and the logs never showed up. it wasn't until we restarted the Elastic Agent pod that we saw logs coming in. this suggests to me that maybe something in Agent stopped working (e.g., some thread of the auto-discovery logioc)...?

all of that said, indeed, when I tested this myself, i was unable to replicate, suggesting that agent normally does track container restarts, but something in agent stopped working such that container restarts were no longer being tracked.

**Comment by gizas** [comment] 2023-02-23 08:59
I left the system up and running and what I observed is that at 17.46 the restarting container stop sending logs
![Screenshot 2023-02-23 at 10 14 10 AM](https://user-images.githubusercontent.com/1685415/220856897-2ee8618d-dc16-4c3b-bbad-cd4a5c63ade8.png)

Find attached `grep -i error` logs from agent:
[logs_error.json.txt](https://github.com/elastic/integrations/files/10811657/logs_error.json.txt)

Around 15.46 I cannot see something related with the absence of or logs for the given container. The logs from other containers/ pods are coming
See below errors from given timeperiod:
```json
"log.level":"info","@timestamp":"2023-02-22T15:43:16.256Z","message":"Non-zero metrics in the last 30s","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"filestream-e364ca80-b298-11ed-9849-9ff19589477e","type":"filestream"},"log":{"source":"filestream-e364ca80-b298-11ed-9849-9ff19589477e"},"service.name":"filebeat","monitoring":{"ecs.version":"1.6.0","metrics":{"beat":{"cgroup":{"memory":{"mem":{"usage":{"bytes":2339196928}}}},"cpu":{"system":{"ticks":111420,"time":{"ms":4230}},"total":{"ticks":165910,"time":{"ms":5000},"value":165910},"user":{"ticks":54490,"time":{"ms":770}}},"handles":{"limit":{"hard":1048576,"soft":1048576},"open":23},"info":{"ephemeral_id":"6deb529f-4760-4947-9ad0-4a113fece685","uptime":{"ms":3090154},"version":"8.6.1"},"memstats":{"gc_next":435500312,"memory_alloc":191566240,"memory_sys":4194304,"memory_total":6501477720,"rss":321732608},"runtime":{"goroutines":15270}},"filebeat":{"events":{"active":0},"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":2}},"output":{"events":{"active":0},"read":{"errors":1}},"pipeline":{"clients":2,"events":{"active":0}}},"registrar":{"states":{"current":0}},"system":{"load":{"1":1.71,"15":1.2,"5":1.57,"norm":{"1":0.342,"15":0.24,"5":0.314}}}}},"log.logger":"monitoring","log.origin":{"file.line":187,"file.name":"log/log.go"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-02-22T16:56:02.074Z","message":"panic: close of closed channel","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"filestream-e364ca80-b298-11ed-9849-9ff19589477e","type":"filestream"},"log":{"source":"filestream-e364ca80-b298-11ed-9849-9ff19589477e"},"ecs.version":"1.6.0"}
```

I can clearly see that logs are being produced from `hello` container:
```bash
root@pas-control-plane:/var/log/containers# cat /var/log/pods/development_multi-container-pod_2ef5500e-4f3c-4326-825c-cf2ca220baac/hello/180.log
2023-02-23T08:40:36.351104927Z stdout F Hello, Kubernetes!
root@pas-control-plane:/var/log/containers# ls -la | grep hello
lrwxrwxrwx 1 root root    96 Feb 23 08:40 multi-container-pod_development_hello-e90fc9027cc6fa0df74ba3aff05b47fb9c1aee623436d3fb333c3ba3efdfe547.log -> /var/log/pods/development_multi-container-pod_2ef5500e-4f3c-4326-825c-cf2ca220baac/hello/180.log
```

Find attached full
[full_logs.txt](https://github.com/elastic/integrations/files/10811763/full_logs.txt)

I can see repeated errors of:
```json
{"log.level":"error","@timestamp":"2023-02-23T08:22:49.585Z","message":"Harvester crashed with: harvester panic with: close of closed channel\ngoroutine 7192 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x68\ngithub.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.startHarvester.func1.1()\n\tgithub.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile/harvester.go:167 +0x58\npanic({0xaaaadc093dc0, 0xaaaadc65b510})\n\truntime/panic.go:844 +0x258\ngithub.com/elastic/beats/v7/libbeat/processors/add_kubernetes_metadata.(*cache).stop(...)\n\tgithub.com/elastic/beats/v7/libbeat/processors/add_kubernetes_metadata/cache.go:97\ngithub.com/elastic/beats/v7/libbeat/processors/add_kubernetes_metadata.(*kubernetesAnnotator).Close(0x40018c1f00?)\n\tgithub.com/elastic/beats/v7/libbeat/processors/add_kubernetes_metadata/kubernetes.go:311 +0x50\ngithub.com/elastic/beats/v7/libbeat/processors.Close(...)\n\tgithub.com/elastic/beats/v7/libbeat/processors/processor.go:58\ngithub.com/elastic/beats/v7/libbeat/publisher/processing.(*group).Close(0x400467d858?)\n\tgithub.com/elastic/beats/v7/libbeat/publisher/processing/processors.go:95 +0x158\ngithub.com/elastic/beats/v7/libbeat/processors.Close(...)\n\tgithub.com/elastic/beats/v7/libbeat/processors/processor.go:58\ngithub.com/elastic/beats/v7/libbeat/publisher/processing.(*group).Close(0x4000402430?)\n\tgithub.com/elastic/beats/v7/libbeat/publisher/processing/processors.go:95 +0x158\ngithub.com/elastic/beats/v7/libbeat/processors.Close(...)\n\tgithub.com/elastic/beats/v7/libbeat/processors/processor.go:58\ngithub.com/elastic/beats/v7/libbeat/publisher/pipeline.(*client).Close.func1()\n\tgithub.com/elastic/beats/v7/libbeat/publisher/pipeline/client.go:167 +0x278\nsync.(*Once).doSlow(0x400467da58?, 0xaaaada55adc8?)\n\tsync/once.go:68 +0x10c\nsync.(*Once).Do(...)\n\tsync/once.go:59\ngithub.com/elastic/beats/v7/libbeat/publisher/pipeline.(*client).Close(0x400467da58?)\n\tgithub.com/elastic/beats/v7/libbeat/publisher/pipeline/client.go:148 +0x5c\ngithub.com/elastic/beats/v7/filebeat/beater.(*countingClient).Close(0x4001411aa8?)\n\tgithub.com/elastic/beats/v7/filebeat/beater/channels.go:145 +0x2c\ngithub.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.startHarvester.func1({0xaaaadc6a09d8?, 0x40010fc340})\n\tgithub.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile/harvester.go:219 +0x6b0\ngithub.com/elastic/go-concert/unison.(*TaskGroup).Go.func1()\n\tgithub.com/elastic/go-concert@v0.2.0/unison/taskgroup.go:163 +0x94\ncreated by github.com/elastic/go-concert/unison.(*TaskGroup).Go\n\tgithub.com/elastic/go-concert@v0.2.0/unison/taskgroup.go:159 +0xc8\n","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"filestream-e364ca80-b298-11ed-9849-9ff19589477e","type":"filestream"},"log":{"source":"filestream-e364ca80-b298-11ed-9849-9ff19589477e"},"log.logger":"input.filestream","service.name":"filebeat","id":"kubernetes-container-logs-etcd-pas-control-plane-5fc0f6d977ead16d46cbffc55eea390bc819c7dd1c46b971bb8592f1b2781ab6","source_file":"filestream::kubernetes-container-logs-etcd-pas-control-plane-5fc0f6d977ead16d46cbffc55eea390bc819c7dd1c46b971bb8592f1b2781ab6::native::3809312-65025","ecs.version":"1.6.0","log.origin":{"file.line":168,"file.name":"input-logfile/harvester.go"},"ecs.version":"1.6.0"}
```
Alwasy related to container-logs-etcd-pas-control-plane so I guess they can be ignored

And also repeated errors like:
```json
{"log.level":"error","@timestamp":"2023-02-23T08:12:49.547Z","message":"Harvester crashed with: harvester panic with: close of closed channel\ngoroutine 6008 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x68\ngithub.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.startHarvester.func1.1()\n\tgithub.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile/harvester.go:167 +0x58\npanic({0xaaaadc093dc0, 0xaaaadc65b510})\n\truntime/panic.go:844 +0x258\ngithub.com/elastic/beats/v7/libbeat/processors/add_kubernetes_metadata.(*cache).stop(...)\n\tgithub.com/elastic/beats/v7/libbeat/processors/add_kubernetes_metadata/cache.go:97\ngithub.com/elastic/beats/v7/libbeat/processors/add_kubernetes_metadata.(*kubernetesAnnotator).Close(0x40018c1f00?)\n\tgithub.com/elastic/beats/v7/libbeat/processors/add_kubernetes_metadata/kubernetes.go:311 +0x50\ngithub.com/elastic/beats/v7/libbeat/processors.Close(...)\n
```
@rdner  Trying to figure out if they are related to our problem or seem related to this https://github.com/elastic/sdh-beats/issues/3078? 
(cc @cmacknz for any ideas)

**Comment by rdner** [comment] 2023-02-23 09:04
@gizas the panic you observe has been reported before here https://github.com/elastic/beats/issues/34219 and there is fix PR https://github.com/elastic/beats/pull/34647 (draft) that I'm still testing. It will be merged very soon.

**Comment by gizas** [comment] 2023-02-23 09:47
Thank you for this @rdner !

Also for the container not reporting logs I see a resemblance with this https://github.com/elastic/elastic-agent/issues/2269

To sum up, this issue was initially opened in order to clarify the correctness of container.ids reported. So I think agent works ok on this as long as it reports back.

@ty-elastic I have checked the diagnostics from the customer and dont see any matching logs with one proposed here. So I am not sure anymore what customer is suggesting when the `wrong` containter ids. Can they confirm the timpestamp of entries because their container could have stopped sending logs and they see a previous container.id 
Also with your lab in 8.5.x do you see same issue? (Dont know if is a good suggestion to tell them downgrade)

**Comment by rdner** [comment] 2023-03-09 16:01
This should be the actual fix https://github.com/elastic/beats/pull/34761 the PR I mentioned in https://github.com/elastic/integrations/issues/5348#issuecomment-1441407700 helped to expose the root cause.

**Closed** 2023-05-31 12:38 UTC
Labels: Team:Cloudnative-Monitoring
