### ISSUE TITLE
[carbon_black_cloud] Alerts v6 API deprecation

### ISSUE THREAD

**Issue by ebeahan** [elastic/integrations#8757] opened 2023-12-19 14:27 UTC
Per [Carbon Black Alerts v6 API docs](https://developer.carbonblack.com/reference/carbon-black-cloud/platform/deprecated/alerts-api/), the v6 API has been deprecated and will be deactivated in July 2024.

Current `carbon_black_cloud.alerts` data stream [calls](https://github.com/elastic/integrations/blob/main/packages/carbon_black_cloud/data_stream/alert/agent/stream/httpjson.yml.hbs#L17) the v6 API and will need updated.

**Comment by narph** [comment] 2024-02-07 10:39
duplicate of https://github.com/elastic/integrations/issues/7997, closing. Feel free to reopen if required

**Closed by narph** 2024-02-07 10:39 UTC
Labels: enhancement, Integration:CarbonBlackCloud
