### ISSUE TITLE
[8.0] AWS Integration only installs 1 Dashboard?

### ISSUE THREAD

**Issue by zikphil** [elastic/integrations#2696] opened 2022-02-14 18:22 UTC
Hello,

After installing the AWS integrations with most (if not all) sub-integrations, I see that only the RDS Metrics Dashboard was added to my instance even though I would expect to see CloudTrail dashboards, etc...

<img width="1056" alt="CleanShot 2022-02-14 at 13 21 05@2x" src="https://user-images.githubusercontent.com/1538854/153923347-798a498f-02ad-4033-8e85-618cce0c30f0.png">

**Comment by joshdover** [comment] 2022-03-16 18:08
Duplicate of https://github.com/elastic/kibana/issues/127664

**Closed by joshdover** 2022-03-16 18:08 UTC
