### ISSUE TITLE
[azure] missing storage_account_container config option

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/integrations#3006] opened 2022-04-05 20:56 UTC
`storage_account_container` config option is added into Filebeat https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/azureeventhub/config.go#L23 but not documented. Also this option is not exposed in integrations when adding azure package. 

It will be good to check if there are other config options that are missing.

**Comment by hubbleview** [comment] 2022-04-08 14:21
In my test, after applying the integration policy to Fleet-managed agent, Filebeat uses the name pattern `filebeat-LOGTYPE-EVENTHUB` as `storage_account_container`. 

For example, my event hub is named `test_logs`, the setting for auditlogs is ` storage_account_container: filebeat-auditlogs-test_logs`, and for signinlogs, it's `storage_account_container: filebeat-signinlogs-test_logs`. 

However, the issue is, these storage container names are not accepted by Azure:
```
This name may only contain lowercase letters, numbers, and hyphens, and must begin with a letter or a number. Each hyphen must be preceded and followed by a non-hyphen character. The name must also be between 3 and 63 characters long.
```

**Comment by zmoog** [comment] 2022-04-13 09:57
> For example, my event hub is named `test_logs`

Hey @hubbleview, which version of Filebeat did you use in your testing?

In the current version of Filebeat, the `azureeventhub` input type [checks explicitly](https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/azureeventhub/config.go#L52-L70) for this kind of situation and exits returning the following error message:

```text
Exiting: Failed to start crawler: \
starting input failed: error while initializing input: \
reading azure-eventhub input config: rune 26 of storage_account_container \
(filebeat-activitylogs-test_logs) is not a lowercase letter, number or dash accessing config
```

Given the circumstances, do you think this behavior is adequate, or would you expect something different?

**Comment by hubbleview** [comment] 2022-04-14 03:13
I was testing in 8.0 stack. 

When I was using standalone Filebeat with azure-eventhub input, with storage account container `testlogs` created before integration, auditlogs and signinlogs were ingested perfectly fine.
```
filebeat.inputs:
- type: azure-eventhub
  eventhub: "test_logs"
  consumer_group: "$Default"
  connection_string: "Endpoint=sb://....."
  storage_account: "teststorage"
  storage_account_key: "...."
  storage_account_container: "testlogs"
```

Only when using Fleet-managed agent to configure the integration, because we don't have option for `storage_account_container`, the agent constructs the name pattern of the storage container. 

In my case, my eventhub name happened to have `_` in the name, `test_logs`, so the constructed `storage_account_container` was set to `filebeat-auditlogs-test_logs`, which is not acceptable by Azure, because it doesn't follow the [Azure container name rule](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#container-names). 

Thanks for opening this PR, https://github.com/elastic/beats/pull/31279, with `storage_account_container` option, this issue should be able to be avoided.

**Comment by zmoog** [comment] 2022-04-19 14:53
As discussed with the [obs-cloud-monitoring](https://github.com/orgs/elastic/teams/obs-cloud-monitoring) team, making the [azureeventhub](https://github.com/elastic/beats/tree/main/x-pack/filebeat/input/azureeventhub) config option `storage_account_container` available to the end user could be also considered as an exposure of an implementation detail.

Other options, when using the event hub name [^1] to build the SA container name [^2], include:

1. Replace underscores (`_`) with hyphens (`-`); for example, `test_logs` would become `test-logs`.
1. Remove underscores (`_`); for example, `test_logs` would become `testlogs`.`

These solutions have the downside of allowing a potential collision, if another storage account container with the same name exists.

The potential is real, but after examining again the scenario, these storage account containers are usually created within a dedicated storage account, so the risk still exists but is probably very low.

[^1]: "Event Hub names can contain letters, numbers, periods (.), hyphens (-), and **underscores (_)**, up to 256 characters. Event Hub names must begin and end with a letter or number."
[^2]: "Container names must start or end with a letter or number, and can contain only letters, numbers, and the dash (-) character." — https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#container-names

**Comment by ravikesarwani** [comment] 2022-04-19 15:27
I like the option (1). Replace underscores (_) with hyphens (-) and also make sure to write a message in the logs that this name change was done because of naming constraint in Azure. This is somewhat an edge case and handling it correctly without overburdening the users with another config option in the integration UI is in my mind a better solution.

**Comment by ravikesarwani** [comment] 2022-04-19 15:30
Also we should look to enhance our document https://docs.elastic.co/en/integrations/azure for the change we make here.

**Comment by zmoog** [comment] 2022-06-03 08:58
The only thing missing is the update to the https://docs.elastic.co/en/integrations/azure page. It will look to into how to make it happen and then I'll close the issue right away.

**Comment by zmoog** [comment] 2022-06-06 08:22
The docs update is in progress, thanks to the docs team.

**Closed** 2022-06-06 17:44 UTC
Labels: bug, Team:Cloud-Monitoring
