### ISSUE TITLE
[elastic_agent] system.process.cpu.{total,user,system}.time.ms should be a long, not a date

### ISSUE THREAD

**Issue by hubbleview** [elastic/integrations#4208] opened 2022-09-13 21:28 UTC
Version: Elastic-Agent 1.3.5

Similar as https://github.com/elastic/integrations/issues/3276 for `metrics-elastic_agent.elastic_agent`, fixed by https://github.com/elastic/integrations/pull/3284,  the dataset `metrics-elastic_agent.metricbeat` also has the mapping of `system.process.cpu.xx.time.ms` as date, which should be `long`. The description also needs update. 

The code is [here](https://github.com/elastic/integrations/blob/main/packages/elastic_agent/data_stream/metricbeat_metrics/fields/fields.yml#L26):

https://github.com/elastic/integrations/blob/557ecfd1ed6474e1cec653e1911008821df230ac/packages/elastic_agent/data_stream/metricbeat_metrics/fields/fields.yml#L52-L63

https://github.com/elastic/integrations/blob/557ecfd1ed6474e1cec653e1911008821df230ac/packages/elastic_agent/data_stream/filebeat_metrics/fields/fields.yml#L52-L63

**Comment by andrewkroh** [comment] 2023-07-03 13:06
This is still occurring in Elastic stack 8.8.2 with Elastic Agent package 1.8.0.

<img width="885" alt="Screenshot 2023-07-03 at 09 02 35" src="https://github.com/elastic/integrations/assets/4565752/0522cd9f-4831-4803-bc19-b396cd6c9c71">
<img width="795" alt="Screenshot 2023-07-03 at 09 02 45" src="https://github.com/elastic/integrations/assets/4565752/6c5cd468-3067-47b4-991c-38840a343dc1">

**Comment by andrewkroh** [comment] 2023-07-03 13:15
It looks like 10 of the `*_metrics` data streams in the elastic_agent package have this same problem of using a `date` field for these metrics.

**Comment by lucabelluccini** [comment] 2024-10-28 18:17
This might have been addressed on https://github.com/andrewkroh/integrations/blob/4e6f2dc12bed8437801a7faad18476c5486f1594/packages/elastic_agent/data_stream/metricbeat_metrics/fields/fields.yml

**Comment by andrewkroh** [comment] 2024-10-28 22:23
This must have been fixed by #7872. I can confirm that currently (8882cd426ac) all of the `time.ms` fields are `long` in the elastic_agent package.

**Closed by andrewkroh** 2024-10-28 22:23 UTC
Labels: bug, Integration:elastic_agent, Team:Elastic-Agent-Data-Plane, Team:Obs-InfraObs
