### ISSUE TITLE
Proposal: Start using changelog in packages

### ISSUE THREAD

**Issue by ruflin** [elastic/integrations#82] opened 2020-06-16 11:16 UTC
A package can contain a changelog. Currently propose format can be found here: https://github.com/elastic/package-registry/blob/master/testdata/package/reference/1.0.0/changelog.yml

I'm proposing to start using the changelog in packages even though we don't show it in the UI yet. This should make it easy when looking at a version of a package to see what changed.

**Comment by ph** [comment] 2020-07-01 14:46
@ruflin The above changed ?

**Comment by ruflin** [comment] 2020-07-02 14:20
@ph Link updated.

**Comment by ycombinator** [comment] 2021-02-05 17:48
I think this issue can be considered a duplicate of https://github.com/elastic/package-spec/issues/17? There's more disussion on that issue than here so I would be in favor of closing this one here. Thoughts?

**Comment by masci** [comment] 2021-02-23 14:20
Superseded by https://github.com/elastic/package-spec/issues/17

**Closed by masci** 2021-02-23 14:20 UTC
Labels: Team:Integrations
