### ISSUE TITLE
[Windows]: Error message on adding Windows integration to agent policy

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/integrations#2882] opened 2022-03-24 08:13 UTC
**Kibana version:**  8.2 Snapshot Kibana cloud environment

**Host OS and Browser version:** Windows, All

**Build details:**
```
VERSION: 8.2.0
BUILD: 51365
COMMIT: 130823ac27126f1eca689a186a088f1993fa848a
```

**Preconditions:**
1. 8.2 Snapshot Kibana cloud environment should be available.
2. An agent policy should exist.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Integrations>Windows>Add Windows integration.
3. Observe error on clicking Add integration button.

**Expected Result:**
User should be able to add Windows integration to agent policy without any errors.

**Screenshots:**
![9](https://user-images.githubusercontent.com/77374876/159871359-c7e9f117-4f0d-49ae-8b3f-9566644a21c1.JPG)

**Comment by amolnater-qasource** [comment] 2022-03-24 08:13
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment] 2022-03-24 08:16
Secondary review for this ticket is Done

**Comment by jen-huang** [comment] 2022-03-24 14:58
Closing as duplicate of https://github.com/elastic/kibana/issues/128209.

**Closed by jen-huang** 2022-03-24 14:58 UTC
Labels: bug, Team:Fleet, Integration:Windows, impact:high

**Comment by amolnater-qasource** [comment] 2022-04-01 10:12
Hi @jen-huang 
We have revalidated this issue on latest 8.2 Kibana cloud environment and found it **fixed**.
- We are now able to add Windows integration to agent policy without any errors.

**Build details:**
BUILD: 51685
COMMIT: d18a093a2cf03991b93ea3de6a1054d580d3e82f

**Screenshot:**
![5](https://user-images.githubusercontent.com/77374876/161240363-bb2a47e9-5043-4f65-bd13-25c0328e5399.JPG)

Thanks

**Comment by amolnater-qasource** [comment] 2022-05-11 11:22
### `Bug Conversion`

-  Testcase already exists for this scenario under Fleet test suite at link:
   -  [C35416](https://elastic.testrail.io/index.php?/cases/view/35416)

Thanks
