### ISSUE TITLE
7.11.1 - action [indices:admin/auto_create] is unauthorized for API key id [xxxx] of user [fleet_enroll]

### ISSUE THREAD

**Issue by MarcusCaepio** [elastic/integrations#757] opened 2021-03-02 13:06 UTC
Hi all,
I have created a policy, which only has Cisco integration enabled and collecting the ASA logs on UDP 9001.
In the policy settings, the Agent Monitoring is enabled, but the the logs of these agents tell me, that they are not allowed to index these monitoring events, because the api token is not allowed to create the indices for the fleet_enroll user:

[....] (status=403): {\"type\":\"security_exception\",\"reason\":\"action [indices:admin/auto_create] is unauthorized for API key id [xxx] of user [fleet_enroll]\"}","ecs.version":"1.6.0"}
[....]
I would evaluate this as a bug. After disabling Agent Monitoring in the Policy Settings, the logs disappear.

Cheers,
Marcus

**Comment by ph** [comment] 2021-03-02 20:46
@MarcusCaepio It is possible to have a few loglines before this one? I am interested in the data stream destination you are trying to write to?

**Comment by MarcusCaepio** [comment] 2021-03-03 08:03
Hi @ph 
the logs are written to the metricbeat_monitor-json.log file, so I think it tries to write to "metrics-cisco.asa-default" ?
I have indeed no metric datastreams for the cisco integration in the cluster.
I re-enabled the metrics policy setting, but could not find any information about the target data stream in the logs. 
But based on the new index schema, it should be as I mentioned above.

**Comment by nchaulet** [comment] 2021-03-03 14:32
I was able to reproduce the issue if you create a config without metrics 

I go this message, looks like we are trying to index `system.network`, `system.cpu`, ... it is normal @michalpristas ? 
```
{
  "log.level": "warn",
  "@timestamp": "2021-03-03T09:27:01.432-0500",
  "log.logger": "elasticsearch",
  "log.origin": {
    "file.name": "elasticsearch/client.go",
    "file.line": 408
  },
  "message": "Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Time{wall:0xc008050d0dd28f18, ext:123307184953, loc:(*time.Location)(0xa650860)}, Meta:null, Fields:{\"agent\":{\"ephemeral_id\":\"1d42be8b-49b2-45e0-a2d4-ee3e31f02565\",\"hostname\":\"Nicolass-MacBook-Pro.local\",\"id\":\"9f008dcb-f3b1-42cb-a683-9f2af3d9c446\",\"name\":\"Nicolass-MacBook-Pro.local\",\"type\":\"metricbeat\",\"version\":\"7.11.2\"},\"ecs\":{\"version\":\"1.7.0\"},\"event\":{\"dataset\":\"system.process\",\"duration\":118207921,\"module\":\"system\"},\"host\":{\"architecture\":\"x86_64\",\"hostname\":\"Nicolass-MacBook-Pro.local\",\"id\":\"A4D26E5E-1CCB-57BF-8AB6-39A955488947\",\"ip\":[\"fe80::aede:48ff:fe00:1122\",\"fe80::eb:d7cc:a9ad:bf5f\",\"192.168.68.112\",\"fe80::146c:a2ff:feb4:3978\",\"fe80::146c:a2ff:feb4:3978\",\"fe80::c5:579d:2c8e:f6f8\",\"fe80::4ba1:75ff:5695:2473\",\"fe80::f0b4:c93:68e8:6ee0\",\"fe80::bb6e:7e7c:8a3e:20ac\",\"fe80::96ce:4992:6adc:ed9e\",\"fe80::b4f6:76d0:c4d4:47dc\"],\"mac\":[\"ac:de:48:00:11:22\",\"a6:83:e7:4e:a2:42\",\"a4:83:e7:4e:a2:42\",\"06:83:e7:4e:a2:42\",\"16:6c:a2:b4:39:78\",\"16:6c:a2:b4:39:78\",\"82:46:af:c6:8c:01\",\"82:46:af:c6:8c:00\",\"82:46:af:c6:8c:05\",\"82:46:af:c6:8c:04\",\"82:46:af:c6:8c:01\"],\"name\":\"Nicolass-MacBook-Pro.local\",\"os\":{\"build\":\"19H512\",\"family\":\"darwin\",\"kernel\":\"19.6.0\",\"name\":\"Mac OS X\",\"platform\":\"darwin\",\"version\":\"10.15.7\"}},\"metricset\":{\"name\":\"process\",\"period\":10000},\"process\":{\"args\":[\"/Users/nicolas/.nvm/versions/node/v14.16.0/bin/node\",\"/Users/nicolas/Workspace/kibana/packages/kbn-optimizer/target/worker/run_worker.js\"],\"command_line\":\"/Users/nicolas/.nvm/versions/node/v14.16.0/bin/node /Users/nicolas/Workspace/kibana/packages/kbn-optimizer/target/worker/run_worker.js\",\"cpu\":{\"pct\":0.000000,\"start_time\":\"2021-03-03T14:00:49.633Z\"},\"executable\":\"/Users/nicolas/.nvm/versions/node/v14.16.0/bin/node\",\"memory\":{\"pct\":0.025100},\"name\":\"node\",\"pgid\":2534,\"pid\":2657,\"ppid\":2545,\"state\":\"running\"},\"service\":{\"type\":\"system\"},\"system\":{\"process\":{\"cmdline\":\"/Users/nicolas/.nvm/versions/node/v14.16.0/bin/node /Users/nicolas/Workspace/kibana/packages/kbn-optimizer/target/worker/run_worker.js\",\"cpu\":{\"start_time\":\"2021-03-03T14:00:49.633Z\",\"total\":{\"norm\":{\"pct\":0.000000},\"pct\":0.000100,\"value\":602875.000000}},\"memory\":{\"rss\":{\"bytes\":861937664,\"pct\":0.025100},\"share\":0,\"size\":7682826240},\"state\":\"running\"}},\"user\":{\"name\":\"nicolas\"}}, Private:interface {}(nil), TimeSeries:true}, Flags:0x0, Cache:publisher.EventCache{m:common.MapStr(nil)}} (status=403): {\"type\":\"security_exception\",\"reason\":\"action [indices:admin/auto_create] is unauthorized for API key id [AY95-HcBd7o1_TjwqNJS] of user [fleet_enroll]\"}",
  "ecs.version": "1.6.0"
}
```

**Comment by michalpristas** [comment] 2021-03-03 15:14
@nchaulet you removed system from policy? these should be part of system integration

**Comment by nchaulet** [comment] 2021-03-03 15:16
I remove system yes I have a policy with only nginx logs

**Comment by michalpristas** [comment] 2021-03-03 15:20
and is monitoring enabled?

**Comment by nchaulet** [comment] 2021-03-03 15:30
Yes monitoring is enabled both for logs and metrics

**Comment by michalpristas** [comment] 2021-03-09 10:03
behavior reproduced
the problem here will be probably default system module configuration.

extracted datasets used are 
```
system.cpu
system.filesystem
system.fsstat
system.load
system.memory
system.network
system.process
system.socket
system.uptime
```

which matches configuration in https://github.com/elastic/beats/blob/master/metricbeat/modules.d/system.yml
agent sends configuration without these to metricbeat.

after this module is disabled no errors are found, so i would say it is expected and default behavior of metricbeat

cc @ruflin

**Comment by EricDavisX** [comment] 2021-03-09 14:28
And I'd really appreciate a summary / confirmation, too.  As I see understand it currently... a user turned on Monitoring in an Integration, but removed System Integration Policy.  If we can enable functionality that requires System in other Integrations, then we need a way to validate in the UI and if not set up, Warn user or prevent it from being set as such. 

If I'm mis-understanding, happy to hear the clarification.  As I understand it, I'd cite this as a medium priority, the work-around is easy, and many folks won't disable / remove System anyways.

**Comment by michalpristas** [comment] 2021-03-09 14:44
i think we can suppress this behavior by setting `config.modules.path` to empty string if this is desirable

**Comment by nchaulet** [comment] 2021-03-09 15:00
An example of a policy that we cause that issue, only nginx logs (no metrics)
```
id: cdd6fe50-80e4-11eb-ac68-dd1f1278a63c
revision: 3
outputs:
  default:
    type: elasticsearch
    hosts:
      - 'http://elasticsearch:9200'
agent:
  monitoring:
    enabled: true
    use_output: default
    logs: true
    metrics: true
inputs:
  - id: faf9ab7b-1f97-4763-91f2-3bc03fc07321
    name: nginx-1
    revision: 2
    type: logfile
    use_output: default
    meta:
      package:
        name: nginx
        version: 0.3.10
    data_stream:
      namespace: default
    streams:
      - id: logfile-nginx.access-faf9ab7b-1f97-4763-91f2-3bc03fc07321
        data_stream:
          dataset: nginx.access
          type: logs
        exclude_files:
          - .gz$
        paths:
          - /var/log/nginx/access.log*
        processors:
          - add_locale: null
      - id: logfile-nginx.error-faf9ab7b-1f97-4763-91f2-3bc03fc07321
        data_stream:
          dataset: nginx.error
          type: logs
        exclude_files:
          - .gz$
        paths:
          - /var/log/nginx/error.log*
        multiline:
          negate: true
          pattern: '^\d{4}\/\d{2}\/\d{2} '
          match: after
        processors:
          - add_locale: null
fleet:
  kibana:
    protocol: http
    hosts:
      - 'kibana:5601'
 ```

**Comment by ph** [comment] 2021-03-09 15:38
I understand now, it's because the running metricbeat uses some default values? is that correct?

**Comment by ph** [comment] 2021-03-10 13:38
@michalpristas and @nchaulet If I understand correctly, the metricbeat sidecar that elastic agent starts is somehow enabling a module shipped with Metricbeat. This means an input is running without any data_stream.* fields configured and  metricbeat is actually trying to send events to metricbeat-* indices. Is that the actual problem?

**Comment by michalpristas** [comment] 2021-03-10 16:57
@ph yes this seems correct, metricbeat tries to use system module which is enabled by default and we dont provide any config for this one so it fallbacks also to defaults.

**Comment by ruflin** [comment] 2021-03-15 12:44
:-( Seems we need to overwrite the default metricbeat magic here.

**Comment by michalpristas** [comment] 2021-03-17 16:16
i looked into this one a bit more today and figured out what was going on. 
on monitoring beats we were not using pregenerated specs.
for metricbeat we already have a post install step which disables system module but as this post install were lacking in for monitoring beats it started with that module enabled.

we fixed that and this should not be present from 7.12 on

**Comment by michalpristas** [comment] 2021-03-18 07:41
@ruflin should we backport this fix to 7.11 or keep it in 12 and x

**Comment by ruflin** [comment] 2021-03-18 07:52
@michalpristas How big is the change that would have to go into 7.11. Can you reference a PR that we did for 7.12?

**Comment by michalpristas** [comment] 2021-03-18 07:59
this was part of much bigger work and `fixed by accident` fix is pretty straightforward. instead of constructing struct manually we just load from Supported map.
but as you correctly mentioned, i don't see upcoming release for 7.11. we can backport it just to be sure but i think this is rather an non critical edge case

**Comment by ph** [comment] 2021-04-28 18:20
@michalpristas I will close this issue but can you reference the PR ?

**Closed by ph** 2021-04-28 18:20 UTC
Labels: Team:Agent

**Comment by michalpristas** [comment] 2021-04-30 10:44
mentioned PR: https://github.com/elastic/beats/pull/23843
