### ISSUE TITLE
Add Containerd module

### ISSUE THREAD

**Issue by akshay-saraswat** [elastic/integrations#2164] opened 2021-11-16 07:44 UTC
# Add Containerd module

Contianerd is a container runtime with an emphasis on simplicity, robustness, and portability. It is often used in Kubernetes. It is becoming more popular in Cloud because vendors like GCP and Azure are now providing containerd as a default runtime for GKE and AKS clusters respectively.

https://containerd.io/

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

**Comment by tetianakravchenko** [comment] 2022-01-19 09:09
duplicate of https://github.com/elastic/integrations/issues/2373

**Closed by tetianakravchenko** 2022-01-19 09:09 UTC
Labels: release-pending
